### ISSUE TITLE
Making google map height responsive using flexbox 

### ISSUE THREAD

**Issue by jeffrey008** [asennikov/ember-g-map#72]
Hello guys, I am trying to make my google map responsive, say, the map fits my div when I resize. Here is what I did:

``` html 
.flex-container{
    display: flex;
    flex-direction:column;
    height:100%;
}
.g-map-canvas {
    width:100%;
    height: 100%;
}
<div class="flex-container">
    <div style="flex:1" >
      {{#g-map  markersFitMode="init" as |context|}}
      {{/g-map}}
    </div>
    <div style="flex-basis:256px">
       something goes here
    </div>
</div>
```

But the result is, I see nothing because the `<div id="ember589" class="ember-view g-map" >`  has height = 0.

The problem is fixed when I set the `.g-map height = 100%`, but that sounds a bit hacky to me, since the way we should set the map should be using g-map-canvas.

Is there any better way to achieve my result rather than this hacky method? Thanks.

**Comment by asennikov** [comment]
Your solution is fine, see https://github.com/asennikov/ember-g-map/issues/75, also in that particular case with flexbox you can do it a bit differently:

```css
.flex-container{
    display: flex;
    flex-direction: column;
    height: 100%;
}
.g-map-canvas {
    width: 100%;
    height: 100%;
}
.my-beautiful-map {
    flex: 1;
}
```
```hbs
<div class="flex-container">
    {{#g-map class="my-beautiful-map" markersFitMode="init" as |context|}}
       ...
    {{/g-map}}
    <div style="flex-basis:256px">
       something goes here
    </div>
</div>
```
