### ISSUE TITLE
Make google map have 100% width and height as parent div

### ISSUE THREAD

**Issue by jeffrey008** [asennikov/ember-g-map#75]
Hello guys, I have a div which has dynamic width and height, and the dimensions are determined after the webpage is loaded. In order to make my google map take to full width and height of the div, I need to do the following:
```css
.g-map{
    height:100%;
}
.g-map-canvas {
    width:100%;
    height: 100%;
}
```
Which is not the mentioned as the readme file. Should we add this into readme file? Or am I using a wrong approach to solve this problem?
Please give me some help on this. Thank you.

**Comment by asennikov** [comment]
Hmm, you're right, I've almost forgot that there's intermediate `<div class="g-map">` element in the layout. Yeah, your solution is fine, another approach would be to add custom class to the component declaration:

```hbs
{{#g-map class="full-height" markersFitMode="live" options=customOptions as |context|}}
  ...
{{/g-map}}
```
which is something like
```css
.full-height {
  height: 100%;
  position: relative;
}
```

Anyway, fill free to submit PR to the docs.
